name: tooth_registration
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  # 科学计算基础库
  - numpy>=1.21.0
  - scipy>=1.7.0
  - matplotlib>=3.5.0
  - pandas>=1.3.0
  
  # 图像处理 (conda版本)
  - opencv>=4.5.0
  - pillow>=8.3.0
  - scikit-image>=0.18.0
  - scikit-learn>=1.0.0
  
  # 数据可视化
  - seaborn>=0.11.0
  - plotly>=5.0.0
  
  # Jupyter支持
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  
  # 开发工具
  - pytest>=6.2.0
  - black>=21.0.0
  - flake8>=3.9.0
  
  # pip安装的包
  - pip:
    - opencv-contrib-python>=4.5.0
    - loguru>=0.5.0
    - tqdm>=4.62.0
    - PyYAML>=5.4.0
    - pytest-cov>=2.12.0